name: Deploy Action

on:
  workflow_dispatch:
    inputs:
      action:
        required: true
        default: 'deploy'
        options:
          - deploy

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"